{
 "title": "Multicluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(destination_workload_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Istio version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (cluster, version) (pilot_info{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pilot XDS Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (cluster, type) (irate(pilot_xds_pushes{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "{{cluster}} {{type}}"
    }
   ]
  },
  {
   "title": "ADS Monitoring",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pilot_virt_services{job=\"pilot\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}} Virtual Services"
    },
    {
     "expr": "pilot_services{job=\"pilot\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}} Services"
    },
    {
     "expr": "pilot_xds{job=\"pilot\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}} Connected Endpoints"
    }
   ]
  },
  { "title": "Data Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Incoming Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "istio_requests_total:destination:rate1m{cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\"}",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "istio_requests_total:source:rate1m{cluster=~\"$cluster\", source_workload_namespace=~\"$namespace\"}",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Incoming Requests Rate in Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (cluster) (istio_requests_total:destination:rate1m{cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Requests Rate in Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (cluster) (istio_requests_total:source:rate1m{cluster=~\"$cluster\", source_workload_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Istio TCP Sent Bytes at Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "istio_tcp_sent_bytes_total:source:rate1m{cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\"}",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio TCP Received Bytes at Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "istio_tcp_received_bytes_total:source:rate1m{cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\"}",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Istio TCP Sent Bytes by East West Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (cluster) (istio_tcp_sent_bytes_total:source:rate1m{source_workload=\"istio-eastwestgateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Istio TCP Received Bytes by East West Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (cluster) (istio_tcp_received_bytes_total:source:rate1m{source_workload=\"istio-eastwestgateway\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}